#!/bin/bash

### 12/11/2025 Initial Version

clear
while true
do
    echo
    read -rp "Input the CR number which the config_estimator output was collect(i.e. CHG0239574): " NO4CR
    
    if [ ! -z "$NO4CR" ]
    then
        break
    else
        echo "CR number can not be blank. Please input the CR Number again ..."
		echo ""
     fi
done

while true
do
    echo
    read -rp "Input the actual total hours for MHM data redistribution(i.e. 15.5): " TIME4CR
    
    if [ ! -z "$TIME4CR" ] && [ "$TIME4CR" -gt 0 ]
    then
        break
    else
        echo "Time can not be blank or 0. Please input the actual total hours again ..."
		echo ""
     fi
done

while true
do
    echo;echo "Files found in the directory:";ls;echo;echo
    read -rp "Input the file name of the config_estimator output (default is estimator.txt): " est
    est=${est:-estimator.txt}
    
	ls $est
    if [ $? == 0 ]
    then
        break
    else
        echo "The file is not found. Please input the file name again ..."
		echo ""
     fi
done

while true
do
  echo;echo "Please select a platform type:"
  echo "1. IFX 2.5"
  echo "2. IFX 2.1.1"
  echo "3. IFX 2.1"
  echo "4. VoV"
  echo "5. Amazon Cloud"
  echo "6. Azure Cloud"
  echo "7. Google Cloud"
  
  read -p "Enter the number of your choice (1-7): " choice
  
  case "$choice" in
  1)
    Platform_Type="IFX 2.5" 
    break
    ;;
  2)
    Platform_Type="IFX 2.1.1" 
    break
    ;;
  3)
    Platform_Type="IFX 2.1" 
    break
    ;;
  4)
    Platform_Type="VoV"
    break
    ;;
  5)
    Platform_Type="Amazon Cloud"
    break
    ;;
  6)
    Platform_Type="Azure Cloud"
    break
    ;;
  7)
    Platform_Type="Google Cloud"
    break
    ;;  
  *) 
    echo;echo "Warning:"
    read -p "Invalid choice.Press any key to continue and select again"
    ;;
  esac
done

cp $est rec-est-op-org; 

echo ""
echo "Analysis and Calculation is started. Please wait ..."
echo ""
awk '/^[[:space:]]*[0-9.]+[[:space:]]*(TB|MB|GB|KB)/' $est > uncompressed_size4tbl.out

amps_nfmt=$(grep "current configuration"  rec-est-op-org  | awk '{print $8}');
amps=$(echo "$amps_nfmt" | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')

# If amps is exactly 4 digits (e.g., 1500), format it with a comma (1,500)
#if [[ "$amps" =~ ^[0-9]{4}$ ]]; then
#  amps_fmt=$(sed -E 's/^([0-9])([0-9]{3})$/\1,\2/' <<< "$amps")
#else
#  amps_fmt="$amps"
#fi;

echo Number of Amps before Merge is $amps;
echo;
TB=$(egrep "^[ 0-9]{4}\.[0-9]{2}TB" rec-est-op-org | sort -k1 -nr | grep -c "TB") ;
echo Number of TB TABLES is  $TB;
GB=$(egrep "^[ 0-9]{4}\.[0-9]{2}GB" rec-est-op-org | sort -k1 -nr | grep -c "GB") ;
echo Number of GB TABLES is $GB;
MB=$(egrep "^[ 0-9]{4}\.[0-9]{2}MB" rec-est-op-org | sort -k1 -nr | grep -c "MB") ;
KB=$(egrep "^[ 0-9]{4}\.[0-9]{2}KB" rec-est-op-org | sort -k1 -nr | grep -c "KB") ;
empty=$(awk -v a="$amps" '$3==a' rec-est-op-org | wc -l);
smalltbls=$(( MB + KB ));
small_effective=$(( smalltbls - empty ));
echo Number of MB TABLES is $small_effective;
echo Number of Empty TABLES is $empty;
echo Total Number of Tables is $(( TB + GB + MB + KB ));

Est_redisct=$(grep -A1 "table redistribution time will" rec-est-op-org|grep "for offline reconfig"|awk '{print $3}')
Est_del=$(grep -A1 "table deletion time will" rec-est-op-org|grep "for offline reconfig"|awk '{print $1}')

awk '{ print $1 $2}' uncompressed_size4tbl.out > 1.out
tb=`grep "TB" 1.out | sed "s/TB//g" | awk '{ sum+=$1 } END { print sum }'`
gb=`grep "GB" 1.out | sed "s/GB//g" | awk '{ sum+=$1 } END { print sum/1024 }'`
mb=`grep "MB" 1.out | sed "s/MB//g" | awk '{ sum+=$1 } END { print sum/1024/1024 }'`
kb=`grep "KB" 1.out | sed "s/KB//g" | awk '{ sum+=$1 } END { print sum/1024/1024/1024 }'`
Uncompressed_Size=$(echo | awk -v t=$tb -v g=$gb -v m=$mb -v k=$kb '{ print (t+g+m+k)}')
DB_Size=$(grep "The system has:" rec-est-op-org|awk '{print $7}'|cut -d "T" -f1)

FNAME4EST=${NO4CR}_$(date +%m%d%H%M).out
>$FNAME4EST
echo;echo;echo "The followings are the required inputs for the spreadsheet of time estimation..."
echo "(Version of script 20251211)" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "CR#                 :  " "$NO4CR" "" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Act_Total           :  " "$TIME4CR" "" | tee -a $FNAME4EST 
printf "%-25s %-10s %-10s\n" "Avg_throughput      :  " "$(echo "scale=2; $Uncompressed_Size / $TIME4CR"|bc)" "" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Platform_type       :  " "$Platform_Type" "" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Node#_cur           :  " "$(grep "current configuration has" rec-est-op-org|awk '{print $5}')" "Nodes" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "AMP#_cur            :  " "$(grep "current configuration has" rec-est-op-org|awk '{print $8}')" "AMPs" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Node#_new           :  " "$(grep "new configuration will be" rec-est-op-org|awk '{print $6}')" "Nodes" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "AMP#_new            :  " "$(grep "new configuration will be" rec-est-op-org|awk '{print $9}')" "AMPs" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Est_redisct         :  " "$Est_redisct" "Hours" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Est_del             :  " "$Est_del" "Hours" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Est_Total           :  " "$(echo "$Est_redisct + $Est_del"|bc)" "Hours" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Uncompressed_Size   :  " "$Uncompressed_Size" "TB" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "DB_Size             :  " "$DB_Size" "TB" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Compression_Ratio   :  " "$(echo "scale=2; $Uncompressed_Size / $DB_Size"|bc)" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Empty_tbl#          :  " "$empty" "" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "TB_tbl#             :  " "$TB" "" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "GB_tbl#             :  " "$GB" "" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "MB_tbl#             :  " "$small_effective" "" | tee -a $FNAME4EST
printf "%-25s %-10s %-10s\n" "Total_tbls          :  " "$(awk '/The system has:/ {print $4}' rec-est-op-org)" "" | tee -a $FNAME4EST

rm rec-est-op-org uncompressed_size4tbl.out 1.out
echo;echo "Note:"
read -p "Kindly be reminded to collect and send the output file \"$FNAME4EST\" with James and Lambert.Press any key to exit..."